User meetings view
ziur/efeeder pull request #106
Opened 2016-11-01 01:11 UTC by wdvf

2016-11-01 14:12 UTC, MirkoTV requested changes

2016-11-01 14:12 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UserMeetingsCommand.java
> +package org.jala.efeeder.user;
please remove this header

2016-11-01 14:12 UTC, MirkoTV commented on src/main/webapp/WEB-INF/user/history.jsp
> +<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
Could you see if this taglib is really necessary in this specific file ? (<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>). if yes ignore this please.

2016-11-01 14:12 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/foodmeeting/FoodMeeting.java
> +		this(id, name, imageLink, status, eventDate, eventDate, eventDate, eventDate, null, userOwner);
If I understand this, here we are creating the FoodMeetings without payment time. Is that correct? if so, is there a reason to do that?

2016-11-08 19:45 UTC, wdvf commented
@MirkoTV please check it again

2016-11-08 19:55 UTC, MirkoTV approved these changes

2016-11-08 19:55 UTC, merged