Place command
ziur/efeeder pull request #109
Opened 2016-11-01 19:02 UTC by ricardo6

added tags table, tag_places table and places table.
search by place name, search by tags

2016-11-01 19:21 UTC, DanitzaMachicado requested changes

2016-11-01 19:21 UTC, DanitzaMachicado commented on src/main/java/org/jala/efeeder/places/CreatePlaceCommand.java
> +    private static final String GET_TAG_ID_QUERY = "SELECT id FROM tags WHERE name=?";
Fix tabs

2016-11-01 19:21 UTC, DanitzaMachicado commented on src/main/java/org/jala/efeeder/places/CreatePlaceCommand.java
> +			if(tagId > 0)
According SCiQuest's code conventions "always use {} for statements if or else"

2016-11-01 19:21 UTC, DanitzaMachicado commented on src/main/java/org/jala/efeeder/places/CreatePlaceCommand.java
> +		if (rSet.next())
Please use {}

2016-11-01 19:21 UTC, DanitzaMachicado commented on src/main/java/org/jala/efeeder/places/CreatePlaceCommand.java
> +		PreparedStatement prepareStatement1 = connection.prepareStatement(UPDATE_TAG_PLACES_QUERY);
Improvement name

2016-11-01 19:21 UTC, DanitzaMachicado commented on src/main/java/org/jala/efeeder/places/SearchPlaceCommand.java
> +			return String.format(SEARCH_PLACES_QUERY_PATHERM, term, term, ENTRIES_BY_PAGE, page);
Please use {}

2016-11-08 18:21 UTC, Ramir0 commented on src/main/java/org/jala/efeeder/suggestion/SuggestionsCommand.java
> +	private static final String TOP_FIVE_PLACES_QUERY = "SELECT * FROM places ORDER BY created_at DESC limit 10";
top five places has 10 places as limit ?

2016-11-18 20:33 UTC, 0x3 approved these changes

2016-11-18 20:36 UTC, Ramir0 approved these changes

2016-11-18 20:42 UTC, DanitzaMachicado approved these changes

2016-11-18 20:43 UTC, merged