Wheel decide
ziur/efeeder pull request #16
Opened 2016-09-16 23:29 UTC by alexandercastrojala

2016-09-17 00:14 UTC, rodrigouz approved these changes

2016-09-19 18:59 UTC, rayaviri commented on src/main/java/org/jala/efeeder/wheel/Buyer.java
> +
Si tienes el @Data ya no es necesario los get and set

2016-09-19 19:02 UTC, alexandercastrojala commented on src/main/java/org/jala/efeeder/wheel/Buyer.java
> +
ok :)
(Y)

2016-09-19 19:05 UTC, rayaviri requested changes
you don't need set and get if you use @Data

2016-09-19 19:08 UTC, merged