Remove liquibase listener
ziur/efeeder pull request #32
Opened 2016-10-03 21:28 UTC by rayaviri

Remove the liquibase listener

2016-10-03 21:42 UTC, Ramir0 approved these changes

2016-10-03 22:04 UTC, ziur commented on src/main/webapp/WEB-INF/web.xml
> +		<param-name>liquibase.changelog</param-name>
These parameters are not needed anymore due to the listener was removed.

2016-10-03 22:05 UTC, ziur commented on src/main/webapp/WEB-INF/web.xml
> +		<servlet-name>GreetingServlet</servlet-name>
And could you please remove this servlet :D?

2016-10-03 22:07 UTC, ziur requested changes
Please, remove context params related to liquidbase

2016-10-04 14:13 UTC, ziur approved these changes

2016-10-04 14:13 UTC, ziur commented on src/main/webapp/WEB-INF/web.xml
> +		<param-name>liquibase.datasource</param-name>
This one is not required too

2016-10-04 14:14 UTC, merged