update user
ziur/efeeder pull request #62
Opened 2016-10-14 20:35 UTC by rayaviri

update user

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/image/ImageCommand.java
> +
Remove extra space

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/image/ImageCommand.java
> +
Remove extra spaces

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/login/LoginCommand.java
> +		if(parameters.getParameter("username") == null || parameters.getParameter("password") == null)
move up brackets

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/servlets/CommandServlet.java
> +
Remove extra spaces

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/user/CreateUserCommand.java
> +			if (isNew)
move up the bt

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/user/UserManager.java
> +		if (userName.isEmpty() == false && password.isEmpty() == false) {
improve conditions

2016-10-14 21:10 UTC, ricardo6 commented on src/main/java/org/jala/efeeder/user/UserManager.java
> +			if (users.isEmpty() == false)
improve

2016-10-14 21:10 UTC, ricardo6 commented on src/main/webapp/WEB-INF/user/user.jsp
> +		<div class="row" style="margin-top: 10%;">
move style to a css file

2016-10-14 21:10 UTC, ricardo6 commented on src/main/webapp/WEB-INF/user/user.jsp
> +										<input type="file" name="image" id="image-upload" style="display:none;"/>
move style to a css file

2016-10-14 21:10 UTC, ricardo6 commented on src/main/webapp/WEB-INF/user/user.jsp
> +												<button id="create-button" class="btn btn-primary" type="submit">Add User</button>
try not use breaks, instead use css to move

2016-10-14 21:21 UTC, ziur commented on src/main/java/org/jala/efeeder/image/ImageCommand.java
> +
Remove line

2016-10-17 14:08 UTC, MirkoTV requested changes

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/image/ImageCommand.java
> +		File imagenFile = new File(path);
Please change this "imagenFile" name

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/login/LoginCommand.java
> +		if(parameters.getParameter("username") == null || parameters.getParameter("password") == null)
yes, lets follow java conventions for curly braces.

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UpdateUserCommand.java
> +package org.jala.efeeder.user;
Remove this header please

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/User.java
> +package org.jala.efeeder.user;
Lets remove this header please

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UserCommand.java
> +package org.jala.efeeder.user;
Lets remove this header please

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UserManager.java
> +		if (userName.isEmpty() == false && password.isEmpty() == false) {
@ricardo6 how do you think we can improve this conditions?

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UserManager.java
> +			user = users.get(0);
follo java conventions for curly braces please

2016-10-17 14:08 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/user/UserManager.java
> +			{
move up curly braces

2016-10-17 14:08 UTC, MirkoTV commented on src/main/webapp/assets/js/user.js
> +$(document).ready(function () {
Lets use the jquery shorthand for document ready

2016-10-17 14:08 UTC, MirkoTV commented on src/main/webapp/assets/js/user.js
> +};
This file looks better now!

2016-10-17 14:16 UTC, rayaviri commented on src/main/java/org/jala/efeeder/image/ImageCommand.java
> +		File imagenFile = new File(path);
este no es mi cambio, solo puse los tabs

2016-10-17 14:25 UTC, MirkoTV approved these changes

2016-10-17 14:25 UTC, merged