Setting meeting validation
ziur/efeeder pull request #89
Opened 2016-10-19 13:41 UTC by DanitzaMachicado

- Display correctly date on picker date
- Fix warning on picker date

2016-10-19 15:55 UTC, alexandercastrojala reviewed
only still one comment..after looks well ...

2016-10-19 15:55 UTC, alexandercastrojala commented on src/main/webapp/assets/js/settingMeeting.js
> +
delete white line

2016-10-19 17:24 UTC, alexandercastrojala approved these changes
look well..

2016-10-21 15:04 UTC, MirkoTV requested changes
Good Job!

2016-10-21 15:04 UTC, MirkoTV commented on src/main/java/org/jala/efeeder/foodmeeting/FoodMeeting.java
> +	public java.time.LocalDate getDate() {
Please complete these comments or delete them

2016-10-21 15:14 UTC, MirkoTV approved these changes

2016-10-21 15:15 UTC, merged